name: Trigger Test Generation

on:
  pull_request:
  push:
    
jobs:
  trigger-b:
    runs-on: ubuntu-latest
    steps:
      - name: Call Submission Repository workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.SUBMISSION_REPO_PAT }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/kite24-bit/Submission/actions/workflows/quality-gate.yaml/dispatches \
          -d '{
            "ref":"main",
            "inputs":{
              "repoA":"${{ github.repository }}",
              "pr_number":"${{ github.event.pull_request.number }}"
            }
          }'
